// Regression tests for built-in name substitution in node code.
//
// Bug: a node generated by the AI node generator rendered black, with
//
//   Error while parsing WGSL: :96:18 error: missing initializer for 'let' declaration
//     let temp_8_0 = let in.uv = (0.0) * 2.0 - 1.0;
//
// The generated body opened with `let uv = input0 * 2.0 - 1.0;`. The compiler rewrote built-in
// names with a run of `replace(/\buv\b/g, "in.uv")` passes, which hit the name being declared and
// turned the declaration into `let in.uv = ...`. That is not a declaration, so the line fell
// through to the "pure expression" branch and was wrapped in another `let`, and the whole shader
// failed to parse — hence a black output.
//
// The same passes fed each other (`u_time` -> `g.time` -> `g.g.time`) and clobbered member access
// (an input wired to a UV node substitutes as `in.uv`, which became `in.in.uv`).

import { describe, it, expect } from 'vitest';
import { substituteShaderBuiltins } from '../src/codegen/compilers/UtilityNodes.js';
import { buildWGSL } from '../src/codegen/glslBuilder.js';

// The body the model wrote in the reported bug, verbatim.
const GENERATED_BODY = `let uv = input0 * 2.0 - 1.0;
let mouse = input1.xy * 2.0 - 1.0;
let density = max(input2, 0.0);
let t = input3 * 0.35;
let toMouse = uv - mouse;
let r = length(toMouse);
let swirl = vec2<f32>(-toMouse.y, toMouse.x) * (0.18 / (r + 0.12));
let p = vec3<f32>(uv + swirl, t);
let n1 = sin(dot(p, vec3<f32>(4.7, 6.3, 3.1)));
let n2 = sin(dot(p + n1 * 0.22, vec3<f32>(9.2, -5.4, 6.8)));
let n3 = sin(dot(p + n2 * 0.14, vec3<f32>(15.1, 11.7, -8.3)));
let turbulence = n1 * 0.5 + n2 * 0.3 + n3 * 0.2;
let plume = exp(-r * r * 5.0) * (0.55 + 0.45 * turbulence);
let fluid = saturate(plume * density);
let color = mix(vec3<f32>(0.01, 0.04, 0.08), vec3<f32>(0.08, 0.65, 1.0), fluid);
color + fluid * fluid * vec3<f32>(0.15, 0.5, 0.9)`;

function wgslFor(node) {
  const graph = {
    nodes: [
      node,
      { id: '99', kind: 'OutputFinal', params: {}, inputs: [node.id] },
    ],
    connections: [],
  };
  const result = buildWGSL(graph);
  return typeof result === 'string' ? result : (result.wgsl || result.code || '');
}

describe('substituteShaderBuiltins', () => {
  it('rewrites a built-in used as a value', () => {
    expect(substituteShaderBuiltins('uv * 2.0')).toBe('in.uv * 2.0');
    expect(substituteShaderBuiltins('sin(time)')).toBe('sin(g.time)');
  });

  it('leaves the name being declared alone', () => {
    const out = substituteShaderBuiltins('let uv = (0.0) * 2.0 - 1.0;');
    expect(out).toBe('let uv = (0.0) * 2.0 - 1.0;');
    expect(out).not.toContain('let in.uv');
  });

  it('keeps a declared local shadowing the built-in on later lines', () => {
    const out = substituteShaderBuiltins('let uv = (0.0) * 2.0;\nlet p = uv + 1.0;');
    expect(out).toBe('let uv = (0.0) * 2.0;\nlet p = uv + 1.0;');
  });

  it('still reads the built-in in a declaration that shadows it', () => {
    // WGSL does not have the declared name in scope inside its own initialiser, so the right-hand
    // side here is the built-in.
    expect(substituteShaderBuiltins('let uv = uv * 2.0;')).toBe('let uv = in.uv * 2.0;');
  });

  it('does not rewrite member access', () => {
    expect(substituteShaderBuiltins('(in.uv).x')).toBe('(in.uv).x');
    expect(substituteShaderBuiltins('g.time * 2.0')).toBe('g.time * 2.0');
    expect(substituteShaderBuiltins('sample.uv + other.time')).toBe('sample.uv + other.time');
  });

  it('substitutes each built-in once, not once per pass', () => {
    expect(substituteShaderBuiltins('u_time')).toBe('g.time');
    expect(substituteShaderBuiltins('sin(u_time) + time')).toBe('sin(g.time) + g.time');
    expect(substituteShaderBuiltins('audioEnvelopeBass + audioEnvelope'))
      .toBe('g.audioEnvelopeBass + g.audioEnvelope');
  });

  it('leaves a var-declared local alone', () => {
    const out = substituteShaderBuiltins('var uv: vec2<f32> = vec2<f32>(0.0);\nuv = uv * 2.0;');
    expect(out).not.toContain('in.uv');
  });
});

describe('CustomGLSL codegen with declared input types', () => {
  it('does not emit a declaration whose name was rewritten to a built-in', () => {
    const wgsl = wgslFor({
      id: '8',
      kind: 'CustomGLSL',
      params: {
        code: GENERATED_BODY,
        outputType: 'vec3',
        inputTypes: ['vec2', 'vec2', 'f32', 'f32'],
      },
      inputs: [],
      inputCount: 4,
    });

    // The reported failure, exactly.
    expect(wgsl).not.toContain('let in.uv');
    expect(wgsl).not.toMatch(/=\s*let\b/);
    expect(wgsl).not.toContain('in.in.uv');
    expect(wgsl).not.toContain('g.g.time');
  });

  it('defaults an unconnected pin to the declared type, not to a scalar', () => {
    const wgsl = wgslFor({
      id: '8',
      kind: 'CustomGLSL',
      params: { code: 'input0.x + input0.y', outputType: 'f32', inputTypes: ['vec2'] },
      inputs: [],
      inputCount: 1,
    });

    // `(0.0).x` is not something WGSL will take a swizzle of.
    expect(wgsl).toContain('vec2<f32>(0.0)');
    expect(wgsl).not.toMatch(/\(0\.0\)\s*\.[xyzw]/);
  });

  it('infers vec2 from a multi-component swizzle when no type is declared', () => {
    const wgsl = wgslFor({
      id: '8',
      kind: 'CustomGLSL',
      params: { code: 'input0.xy * 2.0', outputType: 'vec2' },
      inputs: [],
      inputCount: 1,
    });

    expect(wgsl).toContain('vec2<f32>(0.0)');
    expect(wgsl).not.toMatch(/\(0\.0\)\s*\.xy/);
  });
});
