/**
 * Example: Using ComputeNodeBase
 *
 * This example demonstrates how to create and use compute nodes with the unified API.
 */

import { ComputeNodeBase } from '../ComputeNodeBase.js';

/**
 * Example 1: Create a simple noise compute node
 */
export async function createNoiseNode(device) {
  // Create node with configuration
  const noiseNode = new ComputeNodeBase(device, {
    id: 'noise_example_1',
    kind: 'ComputeNoise',
    params: {
      scale: 8.0,
      octaves: 5,
      speed: 0.1,
      colorize: true,
      resolution: '512'
    },
    metadata: {
      label: 'Noise Generator',
      description: 'FBM noise with configurable parameters',
      category: 'Compute'
    }
  });

  // Initialize with WGSL shader code
  const wgslSource = `
    @group(0) @binding(0) var<uniform> params: Uniforms;
    @group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;

    struct Uniforms {
      resolution: vec2<f32>,
      time: f32,
      scale: f32,
      octaves: f32,
      speed: f32,
      pad0: f32,
      pad1: f32
    }

    @compute @workgroup_size(8, 8)
    fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
      let coords = vec2<i32>(global_id.xy);
      let uv = vec2<f32>(global_id.xy) / params.resolution;

      // Simple noise placeholder
      let noise = fract(sin(dot(uv + params.time * params.speed, vec2<f32>(12.9898, 78.233))) * 43758.5453);
      let color = vec4<f32>(noise, noise, noise, 1.0);

      textureStore(outputTexture, coords, color);
    }
  `;

  await noiseNode.initialize(wgslSource, 512, 512, false);

  return noiseNode;
}

/**
 * Example 2: Create a reaction-diffusion node with feedback
 */
export async function createReactionDiffusionNode(device) {
  const rdNode = new ComputeNodeBase(device, {
    id: 'rd_example_1',
    kind: 'ComputeReactionDiffusion',
    params: {
      pattern: 'Coral',
      feedRate: 0.0545,
      killRate: 0.062,
      diffusionA: 1.0,
      diffusionB: 0.5,
      timestep: 1.0,
      resolution: '512'
    }
  });

  // WGSL would be generated by the compiler - this is a simplified example
  const wgslSource = `
    @group(0) @binding(0) var<uniform> params: Uniforms;
    @group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>;
    @group(0) @binding(2) var previousFrame: texture_2d<f32>;

    struct Uniforms {
      resolution: vec2<f32>,
      time: f32,
      feedRate: f32,
      killRate: f32,
      diffusionA: f32,
      diffusionB: f32,
      timestep: f32
    }

    @compute @workgroup_size(8, 8)
    fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
      // Reaction-diffusion implementation here
      let coords = vec2<i32>(global_id.xy);
      let current = textureLoad(previousFrame, coords, 0);

      // Simplified RD step (real implementation would have full algorithm)
      let color = current * 0.99;

      textureStore(outputTexture, coords, color);
    }
  `;

  await rdNode.initialize(wgslSource, 512, 512, true); // true = supports feedback

  return rdNode;
}

/**
 * Example 3: Using the unified API
 */
export async function unifiedApiExample(device) {
  // Create a node
  const node = await createNoiseNode(device);

  // Set uniforms
  node.setUniform('scale', 12.0);
  node.setUniform('speed', 0.5);

  // Or update multiple at once
  node.updateParams({
    octaves: 7,
    colorize: false
  });

  // Dispatch compute shader
  const commandEncoder = device.createCommandEncoder();
  const time = performance.now() / 1000;
  node.dispatch(device, commandEncoder, time);

  // Get output texture for rendering
  node.getOutputTexture();

  // Submit commands
  device.queue.submit([commandEncoder.finish()]);

  // Serialize node state
  const serialized = node.serialize();

  // Later: deserialize and recreate
  ComputeNodeBase.deserialize(device, serialized);
  // Note: Must call initialize() with WGSL after deserialization

  // Cleanup
  node.destroy();
}

/**
 * Example 4: Creating nodes from definitions
 */
export function createFromDefinition(device) {
  const nodeDef = {
    label: "Compute Noise",
    cat: "Compute",
    inputs: 0,
    pinsIn: [],
    pinsOut: ["Texture", "RGB", "R", "G", "B", "A"],
    params: [
      { name: 'scale', type: 'float', default: 8.0, min: 0.1, max: 50.0 },
      { name: 'octaves', type: 'int', default: 5, min: 1, max: 8 },
      { name: 'speed', type: 'float', default: 0.1, min: 0.0, max: 2.0 }
    ],
    description: "Generate procedural noise using compute shader",
    workgroupSize: [8, 8, 1]
  };

  // Create node from definition
  const node = ComputeNodeBase.fromDefinition(
    device,
    nodeDef,
    'ComputeNoise_123',
    { scale: 10.0 } // Override default scale
  );


  return node;
}

/**
 * Example 5: Managing multiple compute nodes
 */
export class ComputeNodeManager {
  constructor(device) {
    this.device = device;
    this.nodes = new Map();
  }

  async addNode(id, kind, params) {
    const node = new ComputeNodeBase(this.device, {
      id,
      kind,
      params
    });

    this.nodes.set(id, node);
    return node;
  }

  getNode(id) {
    return this.nodes.get(id);
  }

  dispatch(encoder, time) {
    for (const [, node] of this.nodes) {
      node.dispatch(this.device, encoder, time);
    }
  }

  serializeAll() {
    const serialized = [];
    for (const [, node] of this.nodes) {
      serialized.push(node.serialize());
    }
    return serialized;
  }

  async deserializeAll(data) {
    for (const nodeData of data) {
      const node = ComputeNodeBase.deserialize(this.device, nodeData);
      this.nodes.set(node.id, node);
      // Note: Must initialize each node with WGSL after deserialization
    }
  }

  destroy() {
    for (const node of this.nodes.values()) {
      node.destroy();
    }
    this.nodes.clear();
  }
}
